FROM ubuntu:xenial

RUN apt-get update && \
    apt-get install -y curl apt-transport-https

RUN curl -L https://packagecloud.io/karkok-nauto/migrate/gpgkey | apt-key add - && \
    echo "deb https://packagecloud.io/karkok-nauto/migrate/ubuntu/ xenial main" > /etc/apt/sources.list.d/migrate.list && \
    apt-get update && \
    apt-get install -y migrate

RUN migrate -version

